### ISSUE TITLE
Send Team Release Notes To Specific Channels

### ISSUE THREAD

**Issue by therynamo** [target/captains-log#38]
## Summary

As a captain's log user, I would like to be able to get notifications to different rooms about my team's release notes, so that I can quickly identify what was released for only my team.

This is also intended to help people send release notes to channels that their team partners can also access, or be aware of. 

## Done When 

1. Teams can opt into sending **their** teams release notes to a separate channel(s).

Example YAML configuration:

```yml
    teams:
      - name: Team Name Here
        color: "#8B008B"
        emoji: "🐱"
        mentions: "<@myTeam>"
        channels:
          - channel1
          - channel2
        issueTracking:
          jira:
            projects:
              - FUNKYTOWN

```

2. The team who opted in would **not** receive a notification unless they released something. (If asked for enough, we can implement a default message for when releases happen to still notify the team of a release.)
